name: Sync Upstream

on:
  schedule:
    # 每天0点执行 (UTC时间16点)
    - cron: '0 16 * * *'
  pull_request:  # 拉取请求触发
    branches:
      - main  # 仅对 main 分支的 PR 触发
  workflow_dispatch:  # 支持手动触发（在 Actions 页面点击 "Run workflow"）

jobs:
  sync:
    # 仅当仓库所有者不是 'babalae' 且 secrets.USER_EMAIL 存在时运行 保证为下游仓库
    if: github.repository_owner != 'babalae'
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
      # Step 1: 检查出你的 Fork 仓库
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          # 可选：指定分支
          ref: main
          # 拉取完整历史记录，便于合并
          fetch-depth: 0

      - name: 设置输入值
        run: |
          UPSTREAM_REPO='https://github.com/babalae/bettergi-scripts-list.git'
          USER_NAME='${{github.repository_owner||github.actor}}'
          USER_EMAIL='${{secrets.USER_EMAIL}}'
          
          echo "UPSTREAM_REPO=$UPSTREAM_REPO" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          
          echo "设置的输入值: REPO_NAME=$REPO_NAME,DEBUG=$DEBUG,GITEE_NAME=$GITEE_NAME,GITHUB_NAME=$GITHUB_NAME"


      # Step 2: 使用 Action 同步上游变更
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.5
        with:
          # 上游仓库 URL（必填）
          target_sync_branch: main
          # 你的 Fork 分支（必填）
          upstream_sync_branch: main
          # 上游仓库（必填，例如 https://github.com/actions/starter-workflows.git）
          upstream_repo: ${{env.UPSTREAM_REPO}}
          # 上游分支（必填）
          upstream_branch: main

          # 可选：测试模式（手动运行时启用，模拟同步而不实际提交）
          sync_test_mode: false

          # 可选：如果上游是私有仓库，需要 PAT Token（否则用默认 GITHUB_TOKEN）
          # upstream_repo_access_token: ${{ secrets.UPSTREAM_PAT }}

          # 必填：用于推送变更到你的 Fork（默认 GITHUB_TOKEN 即可）
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

          # 可选：如果有冲突，是否强制覆盖（小心使用，可能丢失变更）
          force: false

          # 可选：用户名称和邮箱（用于 Git 提交）
          user_name: ${{env.USER_NAME}}
          user_email: ${{env.USER_EMAIL}}

          # 可选：提交消息前缀
          commit_message_prefix: "chore: "

          # 可选：如果有冲突，是否创建 PR 而非直接合并（推荐 true）
          create_pr_if_conflict: true